// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AdminVideoRequestStatus.
const (
	AdminVideoRequestStatusACCEPTED AdminVideoRequestStatus = "ACCEPTED"
	AdminVideoRequestStatusPENDING  AdminVideoRequestStatus = "PENDING"
	AdminVideoRequestStatusREJECTED AdminVideoRequestStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the AdminVideoRequestStatus enum.
func (e AdminVideoRequestStatus) Valid() bool {
	switch e {
	case AdminVideoRequestStatusACCEPTED:
		return true
	case AdminVideoRequestStatusPENDING:
		return true
	case AdminVideoRequestStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for PatchVideoRequestInputStatus.
const (
	PatchVideoRequestInputStatusACCEPTED PatchVideoRequestInputStatus = "ACCEPTED"
	PatchVideoRequestInputStatusPENDING  PatchVideoRequestInputStatus = "PENDING"
	PatchVideoRequestInputStatusREJECTED PatchVideoRequestInputStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the PatchVideoRequestInputStatus enum.
func (e PatchVideoRequestInputStatus) Valid() bool {
	switch e {
	case PatchVideoRequestInputStatusACCEPTED:
		return true
	case PatchVideoRequestInputStatusPENDING:
		return true
	case PatchVideoRequestInputStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for VideoRequestStatus.
const (
	VideoRequestStatusACCEPTED VideoRequestStatus = "ACCEPTED"
	VideoRequestStatusPENDING  VideoRequestStatus = "PENDING"
	VideoRequestStatusREJECTED VideoRequestStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the VideoRequestStatus enum.
func (e VideoRequestStatus) Valid() bool {
	switch e {
	case VideoRequestStatusACCEPTED:
		return true
	case VideoRequestStatusPENDING:
		return true
	case VideoRequestStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for GetPublicVideosParamsSortBy.
const (
	Popular GetPublicVideosParamsSortBy = "popular"
	Recent  GetPublicVideosParamsSortBy = "recent"
)

// Valid indicates whether the value is a known member of the GetPublicVideosParamsSortBy enum.
func (e GetPublicVideosParamsSortBy) Valid() bool {
	switch e {
	case Popular:
		return true
	case Recent:
		return true
	default:
		return false
	}
}

// Defines values for GetPublicVideosParamsType.
const (
	GetPublicVideosParamsTypeChannel GetPublicVideosParamsType = "channel"
	GetPublicVideosParamsTypeVideo   GetPublicVideosParamsType = "video"
)

// Valid indicates whether the value is a known member of the GetPublicVideosParamsType enum.
func (e GetPublicVideosParamsType) Valid() bool {
	switch e {
	case GetPublicVideosParamsTypeChannel:
		return true
	case GetPublicVideosParamsTypeVideo:
		return true
	default:
		return false
	}
}

// AdminInfo defines model for AdminInfo.
type AdminInfo struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
	Image string              `json:"image"`
	Name  string              `json:"name"`
	Role  string              `json:"role"`
}

// AdminInfoResponse defines model for AdminInfoResponse.
type AdminInfoResponse struct {
	Data AdminInfo `json:"data"`
}

// AdminUser defines model for AdminUser.
type AdminUser struct {
	CreatedAt     time.Time           `json:"created_at"`
	Email         openapi_types.Email `json:"email"`
	GoogleId      string              `json:"google_id"`
	Id            openapi_types.UUID  `json:"id"`
	Image         string              `json:"image"`
	Name          string              `json:"name"`
	Role          string              `json:"role"`
	TrackLimit    int                 `json:"track_limit"`
	UpdatedAt     time.Time           `json:"updated_at"`
	VideosTracked int                 `json:"videos_tracked"`
}

// AdminVideoRequest defines model for AdminVideoRequest.
type AdminVideoRequest struct {
	CreatedAt time.Time               `json:"created_at"`
	Id        openapi_types.UUID      `json:"id"`
	Link      string                  `json:"link"`
	Status    AdminVideoRequestStatus `json:"status"`
	User      AdminUser               `json:"user"`
	YoutubeId string                  `json:"youtube_id"`
}

// AdminVideoRequestStatus defines model for AdminVideoRequest.Status.
type AdminVideoRequestStatus string

// AdminVideoRequestsResponse defines model for AdminVideoRequestsResponse.
type AdminVideoRequestsResponse struct {
	Data []AdminVideoRequest `json:"data"`
}

// ApproveVideoRequestInput defines model for ApproveVideoRequestInput.
type ApproveVideoRequestInput struct {
	Link      string             `json:"link"`
	RequestId openapi_types.UUID `json:"request_id"`
	UserId    openapi_types.UUID `json:"user_id"`
	YoutubeId string             `json:"youtube_id"`
}

// BookmarkedVideo defines model for BookmarkedVideo.
type BookmarkedVideo struct {
	BookmarkedAt time.Time          `json:"bookmarked_at"`
	ChannelId    string             `json:"channel_id"`
	ChannelTitle string             `json:"channel_title"`
	CreatedAt    time.Time          `json:"created_at"`
	Description  string             `json:"description"`
	Id           openapi_types.UUID `json:"id"`
	IsActive     bool               `json:"is_active"`
	Link         string             `json:"link"`
	PublishedAt  time.Time          `json:"published_at"`
	Thumbnail    string             `json:"thumbnail"`
	Title        string             `json:"title"`
	UpdatedAt    time.Time          `json:"updated_at"`
	UserId       openapi_types.UUID `json:"user_id"`
	Visits       int                `json:"visits"`
	YoutubeId    string             `json:"youtube_id"`
}

// BookmarkedVideosResponse defines model for BookmarkedVideosResponse.
type BookmarkedVideosResponse struct {
	Data []BookmarkedVideo `json:"data"`
}

// CreateVideoRequestInput defines model for CreateVideoRequestInput.
type CreateVideoRequestInput struct {
	Link string `json:"link"`
}

// DashboardMetrics defines model for DashboardMetrics.
type DashboardMetrics struct {
	Bookmarked int `json:"bookmarked"`
	Pending    int `json:"pending"`
	Tracked    int `json:"tracked"`
}

// DashboardMetricsResponse defines model for DashboardMetricsResponse.
type DashboardMetricsResponse struct {
	Data DashboardMetrics `json:"data"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// PatchVideoRequestInput defines model for PatchVideoRequestInput.
type PatchVideoRequestInput struct {
	ProcessedBy     *openapi_types.UUID          `json:"processed_by,omitempty"`
	RejectionReason *string                      `json:"rejection_reason,omitempty"`
	Status          PatchVideoRequestInputStatus `json:"status"`
	UserId          openapi_types.UUID           `json:"user_id"`
}

// PatchVideoRequestInputStatus defines model for PatchVideoRequestInput.Status.
type PatchVideoRequestInputStatus string

// PublicVideosData defines model for PublicVideosData.
type PublicVideosData struct {
	HasMore bool            `json:"has_more"`
	Limit   int             `json:"limit"`
	Page    int             `json:"page"`
	Total   int             `json:"total"`
	Videos  []VideoListItem `json:"videos"`
}

// PublicVideosResponse defines model for PublicVideosResponse.
type PublicVideosResponse struct {
	Data PublicVideosData `json:"data"`
}

// SimilarVideo defines model for SimilarVideo.
type SimilarVideo struct {
	ChannelName string `json:"channel_name"`
	Title       string `json:"title"`
}

// SimilarVideosResponse defines model for SimilarVideosResponse.
type SimilarVideosResponse struct {
	Data []SimilarVideo `json:"data"`
}

// SingleVideoResponse defines model for SingleVideoResponse.
type SingleVideoResponse struct {
	Data VideoWithCounts `json:"data"`
}

// UserInfo defines model for UserInfo.
type UserInfo struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
	Image string              `json:"image"`
	Name  string              `json:"name"`
	Role  string              `json:"role"`
}

// UserInfoResponse defines model for UserInfoResponse.
type UserInfoResponse struct {
	Data UserInfo `json:"data"`
}

// UserVideosResponse defines model for UserVideosResponse.
type UserVideosResponse struct {
	Data []Video `json:"data"`
}

// Video defines model for Video.
type Video struct {
	ChannelId    string             `json:"channel_id"`
	ChannelTitle string             `json:"channel_title"`
	CreatedAt    time.Time          `json:"created_at"`
	Description  string             `json:"description"`
	Id           openapi_types.UUID `json:"id"`
	IsActive     bool               `json:"is_active"`
	Link         string             `json:"link"`
	PublishedAt  time.Time          `json:"published_at"`
	Thumbnail    string             `json:"thumbnail"`
	Title        string             `json:"title"`
	UpdatedAt    time.Time          `json:"updated_at"`
	UserId       openapi_types.UUID `json:"user_id"`
	Visits       int                `json:"visits"`
	YoutubeId    string             `json:"youtube_id"`
}

// VideoAnalyticsResponse defines model for VideoAnalyticsResponse.
type VideoAnalyticsResponse struct {
	Data []VideoTimelineSnapshot `json:"data"`
}

// VideoListItem defines model for VideoListItem.
type VideoListItem struct {
	BookmarkCount int                `json:"bookmark_count"`
	ChannelId     string             `json:"channel_id"`
	ChannelTitle  string             `json:"channel_title"`
	CreatedAt     time.Time          `json:"created_at"`
	Description   string             `json:"description"`
	Id            openapi_types.UUID `json:"id"`
	IsActive      bool               `json:"is_active"`
	IsBookmarked  *bool              `json:"is_bookmarked,omitempty"`
	Link          string             `json:"link"`
	PublishedAt   time.Time          `json:"published_at"`
	Thumbnail     string             `json:"thumbnail"`
	Title         string             `json:"title"`
	UpdatedAt     time.Time          `json:"updated_at"`
	UserId        openapi_types.UUID `json:"user_id"`
	Visits        int                `json:"visits"`
	YoutubeId     string             `json:"youtube_id"`
}

// VideoRequest defines model for VideoRequest.
type VideoRequest struct {
	CreatedAt       time.Time           `json:"created_at"`
	Id              openapi_types.UUID  `json:"id"`
	Link            string              `json:"link"`
	ProcessedAt     *time.Time          `json:"processed_at,omitempty"`
	ProcessedBy     *openapi_types.UUID `json:"processed_by,omitempty"`
	RejectionReason *string             `json:"rejection_reason,omitempty"`
	Status          VideoRequestStatus  `json:"status"`
	UpdatedAt       time.Time           `json:"updated_at"`
	UserId          string              `json:"user_id"`
	YoutubeId       string              `json:"youtube_id"`
}

// VideoRequestStatus defines model for VideoRequest.Status.
type VideoRequestStatus string

// VideoRequestsResponse defines model for VideoRequestsResponse.
type VideoRequestsResponse struct {
	Data []VideoRequest `json:"data"`
}

// VideoTimelineSnapshot defines model for VideoTimelineSnapshot.
type VideoTimelineSnapshot struct {
	ImageUrl     string    `json:"image_url"`
	Link         string    `json:"link"`
	SnapshotTime time.Time `json:"snapshot_time"`
	Title        string    `json:"title"`
}

// VideoWithCounts defines model for VideoWithCounts.
type VideoWithCounts struct {
	BookmarkCount int                `json:"bookmark_count"`
	ChannelId     string             `json:"channel_id"`
	ChannelTitle  string             `json:"channel_title"`
	CreatedAt     time.Time          `json:"created_at"`
	Description   string             `json:"description"`
	Id            openapi_types.UUID `json:"id"`
	IsActive      bool               `json:"is_active"`
	Link          string             `json:"link"`
	PublishedAt   time.Time          `json:"published_at"`
	Thumbnail     string             `json:"thumbnail"`
	Title         string             `json:"title"`
	UpdatedAt     time.Time          `json:"updated_at"`
	UserId        openapi_types.UUID `json:"user_id"`
	Visits        int                `json:"visits"`
	YoutubeId     string             `json:"youtube_id"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// MessageOK defines model for MessageOK.
type MessageOK = MessageResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// GetPublicVideosParams defines parameters for GetPublicVideos.
type GetPublicVideosParams struct {
	Page   *int                         `form:"page,omitempty" json:"page,omitempty"`
	Limit  *int                         `form:"limit,omitempty" json:"limit,omitempty"`
	SortBy *GetPublicVideosParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`
	Type   *GetPublicVideosParamsType   `form:"type,omitempty" json:"type,omitempty"`
	Q      *string                      `form:"q,omitempty" json:"q,omitempty"`
}

// GetPublicVideosParamsSortBy defines parameters for GetPublicVideos.
type GetPublicVideosParamsSortBy string

// GetPublicVideosParamsType defines parameters for GetPublicVideos.
type GetPublicVideosParamsType string

// GetVideoAnalyticsByIDParams defines parameters for GetVideoAnalyticsByID.
type GetVideoAnalyticsByIDParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetSimilarVideosParams defines parameters for GetSimilarVideos.
type GetSimilarVideosParams struct {
	Q string `form:"q" json:"q"`
}

// AdminOAuthCallbackParams defines parameters for AdminOAuthCallback.
type AdminOAuthCallbackParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// UserOAuthCallbackParams defines parameters for UserOAuthCallback.
type UserOAuthCallbackParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// ApproveVideoRequestJSONRequestBody defines body for ApproveVideoRequest for application/json ContentType.
type ApproveVideoRequestJSONRequestBody = ApproveVideoRequestInput

// UpdateVideoRequestJSONRequestBody defines body for UpdateVideoRequest for application/json ContentType.
type UpdateVideoRequestJSONRequestBody = PatchVideoRequestInput

// CreateVideoRequestJSONRequestBody defines body for CreateVideoRequest for application/json ContentType.
type CreateVideoRequestJSONRequestBody = CreateVideoRequestInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetAdminVideoRequests List pending video requests (admin only)
	// (GET /admin/request)
	GetAdminVideoRequests(w http.ResponseWriter, r *http.Request)
	// ApproveVideoRequest Approve video request and fetch details from YouTube API
	// (POST /admin/request)
	ApproveVideoRequest(w http.ResponseWriter, r *http.Request)
	// UpdateVideoRequest Reject or update a video request
	// (PATCH /admin/request/{request_id})
	UpdateVideoRequest(w http.ResponseWriter, r *http.Request, requestId openapi_types.UUID)
	// DeleteBookmark Remove a bookmark
	// (DELETE /api/v1/bookmark/{id})
	DeleteBookmark(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// CreateBookmark Bookmark a video
	// (POST /api/v1/bookmark/{id})
	CreateBookmark(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetDashboardMetrics Get user dashboard metrics
	// (GET /api/v1/dashboard/metrics)
	GetDashboardMetrics(w http.ResponseWriter, r *http.Request)
	// GetPublicVideos List public videos
	// (GET /api/v1/public/videos)
	GetPublicVideos(w http.ResponseWriter, r *http.Request, params GetPublicVideosParams)
	// GetVideoAnalyticsByID Get snapshot timeline for a video
	// (GET /api/v1/public/videos/analytics/{id})
	GetVideoAnalyticsByID(w http.ResponseWriter, r *http.Request, id string, params GetVideoAnalyticsByIDParams)
	// GetSimilarVideos Autocomplete search for similar videos
	// (GET /api/v1/public/videos/autocomplete)
	GetSimilarVideos(w http.ResponseWriter, r *http.Request, params GetSimilarVideosParams)
	// GetPublicVideoByID Get video by ID
	// (GET /api/v1/public/videos/{id})
	GetPublicVideoByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetUserVideoRequests Get video requests made by the current user
	// (GET /api/v1/request)
	GetUserVideoRequests(w http.ResponseWriter, r *http.Request)
	// CreateVideoRequest Submit a video tracking request
	// (POST /api/v1/request)
	CreateVideoRequest(w http.ResponseWriter, r *http.Request)
	// DeleteVideoRequest Delete a video request by ID
	// (DELETE /api/v1/request/{id})
	DeleteVideoRequest(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetUserVideos Get videos submitted by the current user
	// (GET /api/v1/videos)
	GetUserVideos(w http.ResponseWriter, r *http.Request)
	// GetUserBookmarks Get bookmarked videos for the current user
	// (GET /api/v1/videos/bookmarks)
	GetUserBookmarks(w http.ResponseWriter, r *http.Request)
	// AuthAdmin Get authenticated admin info
	// (GET /auth/admin)
	AuthAdmin(w http.ResponseWriter, r *http.Request)
	// AdminOAuthCallback Google OAuth callback for an admin
	// (GET /auth/admin/google/callback)
	AdminOAuthCallback(w http.ResponseWriter, r *http.Request, params AdminOAuthCallbackParams)
	// AdminOAuthLogin Begin Google OAuth for an admin
	// (GET /auth/admin/google/login)
	AdminOAuthLogin(w http.ResponseWriter, r *http.Request)
	// AdminOAuthLogout Clear the admin session
	// (GET /auth/admin/google/logout)
	AdminOAuthLogout(w http.ResponseWriter, r *http.Request)
	// UserOAuthCallback Google OAuth callback for a user
	// (GET /auth/google/callback)
	UserOAuthCallback(w http.ResponseWriter, r *http.Request, params UserOAuthCallbackParams)
	// UserOAuthLogin Begin Google OAuth for a user
	// (GET /auth/google/login)
	UserOAuthLogin(w http.ResponseWriter, r *http.Request)
	// UserOAuthLogout Clear the user session
	// (GET /auth/google/logout)
	UserOAuthLogout(w http.ResponseWriter, r *http.Request)
	// AuthUser Get authenticated user info
	// (GET /auth/user)
	AuthUser(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetAdminVideoRequests List pending video requests (admin only)
// (GET /admin/request)
func (_ Unimplemented) GetAdminVideoRequests(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ApproveVideoRequest Approve video request and fetch details from YouTube API
// (POST /admin/request)
func (_ Unimplemented) ApproveVideoRequest(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateVideoRequest Reject or update a video request
// (PATCH /admin/request/{request_id})
func (_ Unimplemented) UpdateVideoRequest(w http.ResponseWriter, r *http.Request, requestId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteBookmark Remove a bookmark
// (DELETE /api/v1/bookmark/{id})
func (_ Unimplemented) DeleteBookmark(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateBookmark Bookmark a video
// (POST /api/v1/bookmark/{id})
func (_ Unimplemented) CreateBookmark(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetDashboardMetrics Get user dashboard metrics
// (GET /api/v1/dashboard/metrics)
func (_ Unimplemented) GetDashboardMetrics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetPublicVideos List public videos
// (GET /api/v1/public/videos)
func (_ Unimplemented) GetPublicVideos(w http.ResponseWriter, r *http.Request, params GetPublicVideosParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetVideoAnalyticsByID Get snapshot timeline for a video
// (GET /api/v1/public/videos/analytics/{id})
func (_ Unimplemented) GetVideoAnalyticsByID(w http.ResponseWriter, r *http.Request, id string, params GetVideoAnalyticsByIDParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetSimilarVideos Autocomplete search for similar videos
// (GET /api/v1/public/videos/autocomplete)
func (_ Unimplemented) GetSimilarVideos(w http.ResponseWriter, r *http.Request, params GetSimilarVideosParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetPublicVideoByID Get video by ID
// (GET /api/v1/public/videos/{id})
func (_ Unimplemented) GetPublicVideoByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetUserVideoRequests Get video requests made by the current user
// (GET /api/v1/request)
func (_ Unimplemented) GetUserVideoRequests(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateVideoRequest Submit a video tracking request
// (POST /api/v1/request)
func (_ Unimplemented) CreateVideoRequest(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteVideoRequest Delete a video request by ID
// (DELETE /api/v1/request/{id})
func (_ Unimplemented) DeleteVideoRequest(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetUserVideos Get videos submitted by the current user
// (GET /api/v1/videos)
func (_ Unimplemented) GetUserVideos(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetUserBookmarks Get bookmarked videos for the current user
// (GET /api/v1/videos/bookmarks)
func (_ Unimplemented) GetUserBookmarks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AuthAdmin Get authenticated admin info
// (GET /auth/admin)
func (_ Unimplemented) AuthAdmin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AdminOAuthCallback Google OAuth callback for an admin
// (GET /auth/admin/google/callback)
func (_ Unimplemented) AdminOAuthCallback(w http.ResponseWriter, r *http.Request, params AdminOAuthCallbackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AdminOAuthLogin Begin Google OAuth for an admin
// (GET /auth/admin/google/login)
func (_ Unimplemented) AdminOAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AdminOAuthLogout Clear the admin session
// (GET /auth/admin/google/logout)
func (_ Unimplemented) AdminOAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UserOAuthCallback Google OAuth callback for a user
// (GET /auth/google/callback)
func (_ Unimplemented) UserOAuthCallback(w http.ResponseWriter, r *http.Request, params UserOAuthCallbackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UserOAuthLogin Begin Google OAuth for a user
// (GET /auth/google/login)
func (_ Unimplemented) UserOAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UserOAuthLogout Clear the user session
// (GET /auth/google/logout)
func (_ Unimplemented) UserOAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AuthUser Get authenticated user info
// (GET /auth/user)
func (_ Unimplemented) AuthUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAdminVideoRequests operation middleware
func (siw *ServerInterfaceWrapper) GetAdminVideoRequests(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminVideoRequests(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveVideoRequest operation middleware
func (siw *ServerInterfaceWrapper) ApproveVideoRequest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveVideoRequest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateVideoRequest operation middleware
func (siw *ServerInterfaceWrapper) UpdateVideoRequest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "request_id" -------------
	var requestId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", chi.URLParam(r, "request_id"), &requestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "request_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateVideoRequest(w, r, requestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteBookmark operation middleware
func (siw *ServerInterfaceWrapper) DeleteBookmark(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBookmark(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBookmark operation middleware
func (siw *ServerInterfaceWrapper) CreateBookmark(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBookmark(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardMetrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicVideos operation middleware
func (siw *ServerInterfaceWrapper) GetPublicVideos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPublicVideosParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sortBy", r.URL.Query(), &params.SortBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sortBy"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortBy", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicVideos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVideoAnalyticsByID operation middleware
func (siw *ServerInterfaceWrapper) GetVideoAnalyticsByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVideoAnalyticsByIDParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVideoAnalyticsByID(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSimilarVideos operation middleware
func (siw *ServerInterfaceWrapper) GetSimilarVideos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSimilarVideosParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSimilarVideos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicVideoByID operation middleware
func (siw *ServerInterfaceWrapper) GetPublicVideoByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicVideoByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserVideoRequests operation middleware
func (siw *ServerInterfaceWrapper) GetUserVideoRequests(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserVideoRequests(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateVideoRequest operation middleware
func (siw *ServerInterfaceWrapper) CreateVideoRequest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVideoRequest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVideoRequest operation middleware
func (siw *ServerInterfaceWrapper) DeleteVideoRequest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVideoRequest(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserVideos operation middleware
func (siw *ServerInterfaceWrapper) GetUserVideos(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserVideos(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserBookmarks operation middleware
func (siw *ServerInterfaceWrapper) GetUserBookmarks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserBookmarks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthAdmin operation middleware
func (siw *ServerInterfaceWrapper) AuthAdmin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthAdmin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminOAuthCallback operation middleware
func (siw *ServerInterfaceWrapper) AdminOAuthCallback(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminOAuthCallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminOAuthCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminOAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) AdminOAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminOAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminOAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) AdminOAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminOAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UserOAuthCallback operation middleware
func (siw *ServerInterfaceWrapper) UserOAuthCallback(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params UserOAuthCallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserOAuthCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UserOAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) UserOAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserOAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UserOAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) UserOAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserOAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthUser operation middleware
func (siw *ServerInterfaceWrapper) AuthUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/google/login", wrapper.UserOAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/google/logout", wrapper.UserOAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/google/callback", wrapper.UserOAuthCallback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/admin/google/login", wrapper.AdminOAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/admin/google/logout", wrapper.AdminOAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/admin/google/callback", wrapper.AdminOAuthCallback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/user", wrapper.AuthUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/admin", wrapper.AuthAdmin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/public/videos", wrapper.GetPublicVideos)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/public/videos/{id}", wrapper.GetPublicVideoByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/public/videos/autocomplete", wrapper.GetSimilarVideos)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/public/videos/analytics/{id}", wrapper.GetVideoAnalyticsByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/dashboard/metrics", wrapper.GetDashboardMetrics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/videos", wrapper.GetUserVideos)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/videos/bookmarks", wrapper.GetUserBookmarks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/request", wrapper.GetUserVideoRequests)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/request", wrapper.CreateVideoRequest)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/request/{id}", wrapper.DeleteVideoRequest)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/bookmark/{id}", wrapper.DeleteBookmark)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/bookmark/{id}", wrapper.CreateBookmark)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/request", wrapper.GetAdminVideoRequests)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/request", wrapper.ApproveVideoRequest)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/request/{request_id}", wrapper.UpdateVideoRequest)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Ft7j9u4Ef8qBFugLaCuvUkOPfi/fV3gXi5Z7CYtimBh0NLY5q1EaknKqC/wdz+QelKibMmWfVncX+u1",
	"qJnhbx6cB/0N+zyKOQOmJJ58wwJkzJkE8881CR7gJQGp9H8+ZwqY+UjiOKQ+UZSz0a+SM/2d9FcQEf3p",
	"rwIWeIL/MipJj9KncnQnBBcPGRO83W49HID0BY01MTzBU7YmIQ3QSwJi46GYqJWHuEBzHmxQTASJQIGQ",
	"eOvhn7iY0yAAdj7prnz9AS0KzlsPT5kCwUhoXj6fKI8g1iAQGK5bD/8CUpIlfPp5MBEyih3w0C+HoCBA",
	"MvF9kHKRhOFGS/WRq594woLz4fIAkifCB8S4QgvDe+vhL4wkasUF/Q3OKMtVolbAVEYdCXhJqIAA65UZ",
	"Ec3jKogom7IF1//EgscgFE1dECJCQ/1hwUVEFJ5k33hYbWLAEyyVoGypt0gDa12S0MC5LCJL0CsbTxiJ",
	"3A8ED10P9JN8R5Ov2LDLpTO0cmYZhadCGj7/FXylSRdbL2BsQBAQtVcTJYJ1qczbrZy/SBBNjr4AoiCY",
	"EWUhGhAF/1TUbKyBUQ9FLTlfhjBL9fXHq9HDShD/eRbSiKrKc8oULMHEliQOegOypgFwOTO0IXDRddlP",
	"iU1hQzmOli3ZQje4eVUdWvK3msJ/NIXKcXe8SXTUZEjZs1MtUhGVGO7AkkhDdH/38Xb68T328NXNzd39",
	"57tb7OGHu3/f3eiPTw7iSWbge53HeMLWwxueqGTeYp0ujWVSZvuwCGTsLWV0wl/ujwZUQSQ77cxS7LZg",
	"T4Qgmx7hIo4FX0OV2JTFicNUWvUp0tdmHe1CY9d1bR+t5XQtgVzqc8FwzflzRMQzBAYJc36G4acFnnzd",
	"rYp0+darozUvCPbwrdqObBpNsZ+agg9lYXU8DravG+Mih5tXjY9Z5eJzS+RqzokIfgElqC+bDEo03YdB",
	"DCzQLJ0Pu4f7CpvytZJ6F9mPyxkaSHTWlZ33NZhDXgg03DRKM2q3+hps6vl3g9FOctWd5Atdm7knyl91",
	"sLtYcB+khGA237hiEkvCkMxDwBMlEvBc4U+zpJzNBJAsz9770lBnYLdA2hopMzGc+CXzkPppULnNzM5G",
	"bkXkLOKiqqc55yEQlh7/rWlXbCu38kRxRUL3ozQT6hzAjOAfqFRTBdHe8JURz0TLhc/l8cqt7kPqONdt",
	"YN7ZdR9pREMiisPL5u2vCGMQzlpTaEVVl1IoXebZ9PaJM9SRZG3x4PPokbJlmJ9Hx+jKkPgvVasbnjDV",
	"I8rqjPTPWRTnOz8O+AK/XogPaopH2uAeL20poPPHbb7qHVTMWY2dI8p2OSO+ouvWw6Cldoh1xJOrnkKr",
	"VRLNWeYsnYPZYfV+n3JlTSVN+83N86t3AZoVLhZCXhGCq3qrAlIrVG2j8ao25lXygFJ9xSb6tRqMSV8x",
	"Em4U9Qd1s880gpAyeGQkliuujnS7IiXoV+FVA32j1qNy5iwuCgfYOku3768zU+bCO7juzW1fcUZ9XHw4",
	"qn3RremUfurtmQP3n4ZpPbnduyGZSStmiXAH+/YuY0ZwZhTX/Wjplgnb1MuwXArrtfcq6hFlsGbTzNcE",
	"ezQpshdcrSUNIfiJoGrzqNmnnIjuPN5w/kxBD4H0V7XRkF6AJEiZDtD0Sg9JUGi+QWoFyFBA700/HH3S",
	"RJBPwnBOfG3wVNNI38oTywlm5DcBlM3Mq7OMdqk8EtOfwUzl/B2C6SRwl1wHSdQqi4aPZkl+bY539/gZ",
	"Xd1P9bAVfUzpIFN/ImNEiLAAFec50gf2EkK+RGkvSVwU1jbB+etX91N9cIOQKY/Li/HFWAPCY2AkpniC",
	"316ML96aAletjCZHBs2RKM+fJZg/2rDMXG8a4Al+D6rZxjY91spA/c14PNjwcUfT3DGJvE/bahmAIpdv",
	"6+F348s2VoXsI2t8WjV544oNY//6tH3ysEyiiIgNnmCdTKDYKQL6e2ronIWbf5hTkUsHvI72e9nAvubB",
	"Zjhc2xr9Wzs46ON169bvbizLQf3Ww2/Glz3feNeFR+XmxplUnMFma9f46AKUv0IBKEJDiRaCR+h/PPmc",
	"zMH4o2Zl+9joWzmY2JpzTrcomzbxxRzoNZOoXBHRcpuopH25jEnW1MPWp1exkX2twqfTmF9LO/Ykxved",
	"mtKDSWv1pZ80ZUPEtqrMZGI6Wl+O8hN69C0zlgBCUNC0llvzfT6v6WQpQ1jIkQo6Gm1/J9CRdlmCchDb",
	"4286nnpd6B0SW0+Kdw5fbtCWIQf5OGoUlZO5tlSjMbs6YaLROnVzpBnFWuTnTYBTg/oeFNIVHyoARFFl",
	"oJfDa9pD/qicjrRBW50ttNi5uZtYGno2CynRDGBBklDhyaWHI8popOvsS89RbLgJ5lMVF8WxhyPy/4zk",
	"eHwYA8mFut64OeCYx0lIBPaKBkH5jQAfrDqoLPvcnMwyN5/UBUou+f9Z660HkxeLQ8dAMsxp7RppudJv",
	"sqSM6AuSoU6F+QJlhnjYKfxDl1fse6nbbdVp0oTcCF9I0uYsI5K3K4szts137O7m9WZ6O8RJ0dEKdnjN",
	"D1WveaO9pqun8MVCQgvVqvO5SJ7S8Fr6yA7TyxtH2ujybswfZnc6WOdCIJVLpit815FYM8NE8fyi8S4j",
	"tGaq3SL4y077iyj7AGypD5833lnDi3s87LoMni48JqpYerqqYI0kEOGvjJZkjU+rsvZFikrgHCpMHJhQ",
	"DqSo5rTcoSazIC+FD67A3u1/pbh2P5TTpgXYfIOmt5bWO7TFiqnyObpinRtips05cB9sX5pa63xFJIC8",
	"q+onQgBLM9l9VdgZmmBttxH/VD0w/dLb/S+VP0PqZRCPyTyiquhtmK61bo+6mhxFY6xTj6N3R+w76HO8",
	"fn2m2Nd7VY6Qub8ELe/hnDJUOm77OOLkh6xeMSV2Nb04T7SUSBo/0aWTM1Q2gC06gnshvi4WnhDl1nvn",
	"O7AuL0mcF/EGX5PztWCeqFXatm+FWTMyU6qTj8Gsy3Ku3+FZw1Yr/zp9O1sjS8ofAkKQjXZpfjevguUo",
	"/f3TqJirtmKrV5sZ7E05gu1Q6fg8AHxAcS0VUdCrzfI2jbX1H2cGVOjmvuKVIXfZueMs/wXpOY+F4zNk",
	"10w8LWtZusc2RYd8ucuDCi1/MOsaEP9rN8SpXH+TyNfvMIWkLwDYIHu+hmX9fkLHDfNEdduxXni4VS2E",
	"iS+HuOxNCERUSGWRo7Knrn6qz5nX76Y5lEN66imdrn5OdXK2QlWvx9fa97nLx6obPdTF2p3L7+RXSeWW",
	"UWUD+c9VW/MJLfupk+J92YR1Q2rYZMLvlUcYELM0wlAS6zyo1BJL7pMQ3cIaQh5HGiQPm4uCeKVUPBmN",
	"Qr1gxaWa/Dj+cWxuztUGGIIHiblrar0qJyOdfV9k97wuAljrO3G/DwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
